---
title: "CaseStudt2"
author: "matthewchapman"
date: "2022-09-05"
output: 
  html_document:
    keep_md: true
---


library(tidyverse)
urlfile = "https://github.com/WJC-Data-Science/DTS350/raw/master/coral.csv"
mydata <- read_csv(url(urlfile))

mydata

```{r}
ggplot(data = filter(mydata, Entity == "Australasia"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))
```


ggplot(data = filter(mydata, Entity == "Australasia"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))


ggplot(data = filter(mydata, Entity == "Indian Ocean/Middle East"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))
  
ggplot(data = filter(mydata, Entity == "Pacific"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))
  
ggplot(data = filter(mydata, Entity == "West Atlantic"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))
  
ggplot(data = filter(mydata, Entity == "World"), mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))



ggplot(data = mydata, mapping= aes(x = Year, y = Value)) + 
  geom_bar(mapping = aes(fill = Event), stat = "identity") +
  facet_wrap(~ Entity, nrow = 3) + 
  scale_fill_manual("legend", values = c("Moderate bleaching events (1-30% bleached)" = "blue", "Severe bleaching events (>30% bleached)" = "red"))
  
  
  
ggplot(data = mydata) +
  geom_line(mapping = aes(x = Year, y = Value))


The data from the visualizations does suggest that bleaching is becoming the most frequent. In all 5 of of the visualizations, the 2016 bar is among the tallest in the graph. 
