---
title: "T6"
author: "matthewchapman"
date: "2022-09-15"
output: 
  html_document:
    keep_md: TRUE
---
#### Load Libraries 
```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggrepel)
library(downloader)
```

## Different Iris Species Have Different Sizes
#### Petal Length (Max)
```{r}
max_flower <- iris %>%
  group_by(Species) %>%
  summarise(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, max = max(Petal.Length, na.rm=TRUE)) %>%
  filter(max == Petal.Length, Petal.Width != 0.2)
```
#### Petal Width (Max)
```{r}
max_flower_width <- iris %>%
  group_by(Species) %>%
  summarise(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, max = max(Petal.Width, na.rm=TRUE)) %>%
  filter(max == Petal.Width) %>%
  filter(Petal.Length != 6, Petal.Length != 5.7)
```
## PLOT
```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, 
                                  y = Sepal.Width)) +
  geom_point(aes(color = Species, shape = Species)) +
  geom_point(size = 3, shape = 1, color = "black", data = max_flower) +
  geom_text(aes(color = Species, label = "Largest Petal Length"), data = max_flower) +
  geom_point(size = 3, shape = 1, color = "black", data = max_flower_width) +
  geom_text(aes(color = Species, label = "Largest Petal Width"), data = max_flower_width) +
  labs(x = "Sepal Length (cm)",
       y = "Sepal Width (cm)",
       title = "Different Iris Species Have Different Sepal Sizes",
       subtitle = "The Largest Petal Sizes For Each Species Do Not Correspond To The Largest Sepal Sizes",
       caption = "Source: iris") +
  theme(legend.position="bottom")
```


## Scrabble Scores in Age of 'QI' and 'ZA'
#### Import Data
```{r}
ScrabbleData <- read_csv("https://media.githubusercontent.com/media/fivethirtyeight/data/master/scrabble-games/scrabble_games.csv")
ScrabbleData
```
#### Manipulate data
```{r}
ScrabbleAll <- ScrabbleData %>%
  select(date, winnerscore, loserscore) %>%
  pivot_longer(c("winnerscore","loserscore"), names_to = "win-loss", values_to = "score") %>%
  filter(score > 0) %>%
  mutate(year = year(date),
         week = week(date),
         month = month(date)
  )
```
#### Get average scores for each week within time frame
```{r}
SA <- ScrabbleAll %>%
  filter((year == 2005 & month >= 7) | (year == 2006 & month <= 10)) %>%
  group_by(year,month,week) %>%
  summarise(date = max(date), AvgScore = mean(score))
```
#### Datasets for Trend Before and Trend After linear lines
```{r}
SA_B4_11K <- SA %>%
  filter((year == 2005 & month >= 6) | (year == 2006 & month <= 2))

SA_AFTER_11K <- SA %>%
  filter(year == 2006 & month <= 10 & month >= 3)
```
#### Plot
```{r}
ggplot(data = SA, mapping = aes(x= date, y = AvgScore)) +
  geom_point() +
  labs(x = "",
       y = "Average Score",
       title = "Scrable Scores in the age of 'QI' and 'ZA'",
       subtitle = "Weekly average scores before and after the addition of around 11,000 words to the Srabble dictionary",
       caption = "Source: FiveThirtyEight") +
  geom_vline(xintercept = as.Date("2006-03-01"),linetype= "dashed") +
  scale_x_date(date_labels = "%b '%y", date_breaks = "3 months", minor_breaks = NULL) +
  geom_text(aes(label = "March 1 Dictionary Updated", x = as.Date("2006-03-01"), y = 390), size =3) +
  theme_bw() +
  geom_text(aes(label = "Trend Before", x = as.Date("2005-12-01"), y = 381), size =3, color="orange") +
  geom_text(aes(label = "Trend After", x = as.Date("2006-07-01"), y = 381), size =3, color="blue") +
  geom_smooth(data = SA_B4_11K, mapping = aes(x = date, y = AvgScore),method='lm',color="orange") +
  geom_smooth(data = SA_AFTER_11K, mapping = aes(x = date, y = AvgScore),method='lm',color="blue")
```

