---
title: "Task 10"
author: "matthewchapman"
date: "2022-09-29"
output: 
  html_document:
    keep_md: TRUE
---
#### Libraries
```{r, results='hide',message=FALSE}
library(devtools)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

#### Download Data
```{r,message=FALSE}
devtools::install_github("drsimonj/ourworldindata")
fh <- ourworldindata::financing_healthcare
fh
```

#### Manipulate Data - fh1
Dataset fh1 gives average child mortality for each continent
```{r,message=FALSE}
fh1 <- fh %>%
  select(year, country, continent, child_mort) %>%
  drop_na() %>%
  mutate(continent = fct_reorder(continent, child_mort)) %>%
  group_by(continent) %>%
  summarise(child_mort = mean(child_mort))
fh1
```

## Plot1
```{r,message=FALSE}
require(scales)

ggplot(data = fh1, mapping = aes(x = continent, y = child_mort, color = child_mort, fill = child_mort)) +
  geom_col() +
  scale_y_continuous(labels = comma) +
  labs(x = "Continent", y = "Average Child Mortality Rate", fill = "Avg Child Mort Rate",color = "Avg Child Mort Rate", title = "Average Child Mortality Accross All Time By Continent")

```


#### Manipulate Data - fh2
Dataset fh2 gives average child mortality rate by decade and continent
```{r,message=FALSE}
fh2 <- fh %>%
  select(year, country, continent, child_mort) %>%
  drop_na() %>%
  group_by(year, continent) %>%
  summarise(year, continent, child_mort = mean(child_mort)) %>%
  mutate(decade = case_when(
    year >= 1760 & year <=1769 ~ 1760,
    year >= 1770 & year <=1779 ~ 1770,
    year >= 1780 & year <=1789 ~ 1780,
    year >= 1790 & year <=1799 ~ 1790,
    year >= 1800 & year <=1809 ~ 1800,
    year >= 1810 & year <=1819 ~ 1810,
    year >= 1820 & year <=1829 ~ 1820,
    year >= 1830 & year <=1839 ~ 1830,
    year >= 1840 & year <=1849 ~ 1840,
    year >= 1850 & year <=1859 ~ 1850,
    year >= 1860 & year <=1869 ~ 1860,
    year >= 1870 & year <=1879 ~ 1870,
    year >= 1880 & year <=1889 ~ 1880,
    year >= 1890 & year <=1899 ~ 1890,
    year >= 1900 & year <=1909 ~ 1900,
    year >= 1910 & year <=1919 ~ 1910,
    year >= 1920 & year <=1929 ~ 1920,
    year >= 1930 & year <=1939 ~ 1930,
    year >= 1940 & year <=1949 ~ 1940,
    year >= 1950 & year <=1959 ~ 1950,
    year >= 1960 & year <=1969 ~ 1960,
    year >= 1970 & year <=1979 ~ 1970,
    year >= 1980 & year <=1989 ~ 1980,
    year >= 1990 & year <=1999 ~ 1990,
    year >= 2000 & year <=2009 ~ 2000,
    year >= 2010 & year <=2019 ~ 2010
  )) %>%
  group_by(decade, continent) %>%
  summarise(child_mort = mean(child_mort))
fh2
```

#### Manipulate Data - fh3
Dataset fh3 gives average child mortality rate across each decade for the whole world
```{r,message=FALSE}
fh3 <- fh %>%
  select(year, country, continent, child_mort) %>%
  drop_na() %>%
  group_by(year) %>%
  summarise(year, child_mort = mean(child_mort)) %>%
  mutate(decade = case_when(
    year >= 1760 & year <=1769 ~ 1760,
    year >= 1770 & year <=1779 ~ 1770,
    year >= 1780 & year <=1789 ~ 1780,
    year >= 1790 & year <=1799 ~ 1790,
    year >= 1800 & year <=1809 ~ 1800,
    year >= 1810 & year <=1819 ~ 1810,
    year >= 1820 & year <=1829 ~ 1820,
    year >= 1830 & year <=1839 ~ 1830,
    year >= 1840 & year <=1849 ~ 1840,
    year >= 1850 & year <=1859 ~ 1850,
    year >= 1860 & year <=1869 ~ 1860,
    year >= 1870 & year <=1879 ~ 1870,
    year >= 1880 & year <=1889 ~ 1880,
    year >= 1890 & year <=1899 ~ 1890,
    year >= 1900 & year <=1909 ~ 1900,
    year >= 1910 & year <=1919 ~ 1910,
    year >= 1920 & year <=1929 ~ 1920,
    year >= 1930 & year <=1939 ~ 1930,
    year >= 1940 & year <=1949 ~ 1940,
    year >= 1950 & year <=1959 ~ 1950,
    year >= 1960 & year <=1969 ~ 1960,
    year >= 1970 & year <=1979 ~ 1970,
    year >= 1980 & year <=1989 ~ 1980,
    year >= 1990 & year <=1999 ~ 1990,
    year >= 2000 & year <=2009 ~ 2000,
    year >= 2010 & year <=2019 ~ 2010
  )) %>%
  group_by(decade) %>%
  summarise(child_mort = mean(child_mort))
fh3

```

## Plot 2
```{r}
ggplot() +
  geom_point(data = fh2, mapping = aes(x = decade,y=child_mort, color = continent)) +
  geom_line(data = fh2, mapping = aes(x = decade,y=child_mort, color = continent)) +
  geom_point(data = fh3, mapping = aes(x = decade, y = child_mort)) +
  geom_line(data = fh3, mapping = aes(x = decade, y = child_mort)) +
  labs(x = "Decade",y = "Average Child Mortality Rate",color = "Continent",title = "Child Mortality by Decade and Continent")

```

