---
title: "CS3"
author: "matthewchapman"
date: "2022-09-13"
output: 
html_document:
  keep_md: TRUE
---

Install Packages/Libraries
```{r}
library(gapminder)
library(tidyverse)
library(ggplot2)
```

Plot1
```{r}
ggplot(data = gapminder) + 
  geom_point(mapping = aes(x = lifeExp, y = gdpPercap, color = continent, size = pop)) +
  scale_y_continuous(trans = "sqrt") +
  facet_wrap(~ year, nrow = 1) +
  theme_bw() +
  ylim(0, 50000)
```

New Data Set With Weighted Mean of GDP
```{r}
gapminder <- group_by(gapminder, continent, year)
WMGDP <- summarise(gapminder,
                   WM = weighted.mean(gdpPercap),
                   population1 = sum(pop)
)
```

Plot2 Part1
```{r}
Plot2 <- ggplot(data = gapminder) + 
  geom_point(mapping = aes(x = year, y = gdpPercap, color = continent, size = pop)) +
  facet_wrap(~ continent) +
  geom_line(aes(x= year, y = gdpPercap, color = continent, group = country))
```

Plot2 Part2
```{r}
Plot2 +
  geom_line(data = WMGDP, aes(x = year, y = WM)) +
  geom_point(data = WMGDP, mapping = aes(x = year, y = WM, size = population1)) +
  theme_bw() +
  ylim(0, 50000)
```

